### ISSUE TITLE
Loading captcha automatically when using QR

### ISSUE THREAD

**Issue by Haldeyr** [TuxedoTako/4chan-xt#42] opened 2024-04-05 00:27 UTC
Is there a way to automatically "Get Captcha" when replying to a thread? The option "Auto-load captcha: Automatically load the captcha in the QR even if your post is empty." doesn't seem to do anything at all

**Comment by TuxedoTako** [comment] 2024-04-05 15:51
Probably related: https://github.com/ccd0/4chan-x/issues/1775, https://github.com/ccd0/4chan-x/issues/1793.

**Comment by Ilya1933** [comment] 2024-08-09 06:46
I came here just to make a thread about this issue, so I will second this thread instead. This feature was already available in 4chan X, but it NEVER worked for me, and it still doesn't. Since someone is now actively developing this extension again, I have hopes that it can be fixed. I'm on Firefox and w10, if that helps.

**Comment by TuxedoTako** [comment] 2024-08-16 15:50
Should be fixed in [2.13.0](https://github.com/TuxedoTako/4chan-xt/releases). Either I'm mistaken, or this was never implemented for the current captcha system.

**Comment by Ilya1933** [comment] 2024-08-16 15:57
It's working perfectly now. Thanks!

**Closed as completed** 2024-08-16 18:54 UTC
Labels: bug

**Comment by gir489returns** [comment] 2024-08-20 18:50
For me this loads 2 "Verify you are human" checkboxes from Cloudflare each time.

![image](https://github.com/user-attachments/assets/7d9e453b-d04c-40e9-a4ed-eaaa870285aa)

However, it could be [4chan captcha solver](https://github.com/drunohazarb/4chan-captcha-solver) interfering with it.

**Comment by AlifianK** [comment] 2024-08-21 17:50
> For me this loads 2 "Verify you are human" checkboxes from Cloudflare each time.
> 
> ![image](https://private-user-images.githubusercontent.com/100792176/359607907-7d9e453b-d04c-40e9-a4ed-eaaa870285aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNTY0MzAsIm5iZiI6MTcyNDI1NjEzMCwicGF0aCI6Ii8xMDA3OTIxNzYvMzU5NjA3OTA3LTdkOWU0NTNiLWQwNGMtNDBlOS1hNGVkLWVhYWE4NzAyODVhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxNjAyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGMxYTljZTc4MTAzNzczZTA2ZjIxNDZiNmRhOWYzZjg2ODNhNTU1ZGEzZjcwNDczOTIwY2VlNjMwMWM0ZTFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZGouYZtjTX8odu7cyclvzo4EtcTKWO8bsLEaKCepytY)
> 
> However, it could be [4chan captcha solver](https://github.com/drunohazarb/4chan-captcha-solver) interfering with it.

Can't reproduce. It works fine for me, even with captcha solver enabled. Maybe test with another browser if the issue persists.
![image](https://github.com/user-attachments/assets/99543f32-568d-4ebf-8dcc-4bd9f2e2c045)

**Comment by gir489returns** [comment] 2024-08-21 18:35
> Can't reproduce. It works fine for me, even with captcha solver enabled. Maybe test with another browser if the issue persists. ![image](https://private-user-images.githubusercontent.com/50392169/360023887-99543f32-568d-4ebf-8dcc-4bd9f2e2c045.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNjU2MDYsIm5iZiI6MTcyNDI2NTMwNiwicGF0aCI6Ii81MDM5MjE2OS8zNjAwMjM4ODctOTk1NDNmMzItNTY4ZC00ZWJmLThkY2MtNGJkOWYyZTJjMDQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDE4MzUwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMTYzZWUyOTdhMWYxYTFiZWZmY2Y3ZDE0NTBlMWYwYzEzZDhkZDUyN2ZjNTVkYTE0MzdmYzdiNzk5MzMyYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0fTIxttHvVbAJRC-rWkkO4XoGyWcnaGYkgl4J973z8o)

It is only the Cloudflare box that is duplicated. The 4chan CAPTCHA loads fine after I pass the Cloudflare checks.

**Comment by gir489returns** [comment] 2024-08-21 19:51
![image](https://github.com/user-attachments/assets/179c05e5-6ef1-404c-b0e7-52ee1e814c48)

I just tried it on the latest version of Chrome only running Tampermonkey with 4chan-XT and the 4chan captcha solver.

**Comment by Haldeyr** [comment] 2024-08-21 20:44
> For me this loads 2 "Verify you are human" checkboxes from Cloudflare each time.
> 
> ![image](https://private-user-images.githubusercontent.com/100792176/359607907-7d9e453b-d04c-40e9-a4ed-eaaa870285aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNzMzMDEsIm5iZiI6MTcyNDI3MzAwMSwicGF0aCI6Ii8xMDA3OTIxNzYvMzU5NjA3OTA3LTdkOWU0NTNiLWQwNGMtNDBlOS1hNGVkLWVhYWE4NzAyODVhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQyMDQzMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NjkyNDJiNzNjN2Y2NmEzYjRiZjcwM2QwMzk0NjgwNWY3ZWFiZTJjYWUyZGVkY2U2NWYzY2FhZWJkZGEwZmNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8eDAO6VKamu6nP_bJKltllkWY9MDvRvUfu0k_XsBNLo)
> 
> However, it could be [4chan captcha solver](https://github.com/drunohazarb/4chan-captcha-solver) interfering with it.

This only happens when I  manually click "Get captcha" while the automatic one is already working on it.

**Comment by gir489returns** [comment] 2024-08-22 18:22
> This only happens when I manually click "Get captcha" while the automatic one is already working on it.

Yes, but for me, if I open the quick reply, it just sits there until I press the button.
