### ISSUE TITLE
Quoted OPs don't display how many replies and images they contain

### ISSUE THREAD

**Issue by anonymousmaggot** [TuxedoTako/4chan-xt#71] opened 2024-06-14 21:45 UTC
This is an old bug inherited from 4chanX. In the native extension, embeds of OPs (that aren't the current thread's OP) display how many replies and images the thread has. 4chanX[T] doesn't. It's a very minor thing but I figured I should make an issue about it anyways.
How embedded OPs look with 4chanXT:
![image](https://github.com/TuxedoTako/4chan-xt/assets/11671472/8ed0fc75-9797-4fcc-b840-f01cb6e14a02)
How embedded OPs look with the native extension:
![image](https://github.com/TuxedoTako/4chan-xt/assets/11671472/f09fccb4-b914-44d3-b72d-a52f95dff999)

**Comment by TuxedoTako** [comment] 2024-06-15 18:02
Should be fixed in [2.10.2](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment] 2024-07-21 00:52
![image](https://github.com/user-attachments/assets/85a7d77e-0a84-45d9-a3b8-0cab9d668868)

As a note, on the native extension, this also works on the index. Currently, XT appears to only do this within a thread.

**Comment by TuxedoTako** [comment] 2024-07-21 18:08
Hover in the catalog was fixed in [2.11.1](https://github.com/TuxedoTako/4chan-xt/releases).

**Comment by saxamaphone69** [comment] 2024-07-22 07:34
![image](https://github.com/user-attachments/assets/0257720e-d5c0-462c-9a61-b5145aefe82e)

Now it's there twice, no hovering.

**Closed as completed** 2024-08-04 16:18 UTC
Labels: bug, feature request

**Comment by saxamaphone69** [comment] 2024-08-05 09:15
I think something has caused a regression along the way. 

There is a "Thread Expansion" option in the settings that lets the user expand a thread while on the index. Generally, this is presented with the `+ 5 posts and 1 image reply omitted.` clickable text - a `.summary` element right after `.opContainer`. Left-clicking it would, on the index, "open" the thread and produce this (including a `.summary-bottom` to close the thread back up once scrolled through if you were on the index). Middle-click would open in a new tab as expected.

![image](https://github.com/user-attachments/assets/a9bd64d7-9c05-4c8e-a513-8b487602a5e2)

Now, regardless of "Thread Expansion" setting, there is a `.summary` that only links to the thread. If "Thread Expansion" is off, then what is currently in place is the expected behaviour.

This may have happened around `2.10`. You'll note in my previous previous picture, the + blah blah, then in my previous post, the omission of the + and the introduction of the clashing behaviour.

**Comment by greentore** [comment] 2024-08-22 19:50
I get double summaries with my custom userstyle that styles `.summary` because `display: none` for `.preview-summary` has too low specificity.

**Comment by TuxedoTako** [comment] 2024-08-24 12:33
I couldn't figure out how to only render the stats on hover, since the function that build the dom for posts doesn't seem to have that context. That's why I ended up just always rendering it, hiding it with css, and then unhiding it when needed.
